filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/vendor/*'
        - 'js/build/*'
        - 'l10n/*'
        - 'templates/*'
        - 'img/*'
        - 'css/*'
        - 'bin/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 600