filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/vendor/*'
        - 'js/build/*'
        - 'l10n/*'
        - 'templates/*'
        - 'img/*'
        - 'css/*'
        - 'bin/*'
        - 'tmp/*'
        - 'appinfo/application.php'

imports:
    #- javascript  disabled because of es6 producing tons of errors
    - php
    - javascript

tools:
    external_code_coverage:
        timeout: 600

checks:
    php:
        # not helpful because there is no setting to tweek the threshold
        duplication: false

build:
    project_setup:
        before:
            - mkdir tmp
            - cd tmp
            - wget https://raw.githubusercontent.com/owncloud/core/master/lib/public/appframework/db/doesnotexistexception.php
            - wget https://raw.githubusercontent.com/owncloud/core/master/lib/public/appframework/db/multipleobjectsreturnedexception.php
            - cd ..