filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/vendor/*'
        - 'js/public/*'
        - 'l10n/*'
        - 'templates/*'
        - 'img/*'
        - 'css/*'
        - 'bin/*'
        
imports:
    - javascript
    - php

tools:
    external_code_coverage: true