sudo: required
dist: trusty
language: php
php:
    - 5.6
    - 7
env:
    global:
        - CORE_BRANCH=stable9
    matrix:
        - DB=pgsql

matrix:
    allow_failures:
        - env: DB=pgsql CORE_BRANCH=master
    include:
        - php: 5.6
          env: DB=sqlite
        - php: 5.6
          env: DB=mysql
        - php: 5.6
          env:  DB=pgsql CORE_BRANCH=master
    fast_finish: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - sudo apt-get -y install python3-setuptools
    - if [[ "$DB" == 'mysql' ]]; then sudo apt-get -y install mariadb-server; fi
    - sudo easy_install3 requests ocdev
    - nvm install 5.6
    - npm install -g npm@latest
    - make dist
    # install core
    - cd ../
    - ocdev setup core --dir owncloud --branch $CORE_BRANCH --no-history
    - mv news owncloud/apps/

before_script:
    - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
    - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"; fi
    # fill owncloud with default configs and enable news
    - cd owncloud
    - mkdir data
    - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
    - ./occ app:enable news
    - ./occ background:cron  # enable default cron
    - ocdev server &
    - cd apps/news

script:
    - make test

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/php-unit.clover

after_failure:
    - sudo cat ../../data/owncloud.log

deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: ds45weacZfcM1kPEFMSBogc3KRxdb77O4V6OfDCWEZTvdCgq5AWY21Rc4fCRL+UYPGtHAWykL96xgoii81uuKEK+eqyJtOlrp53EGHsyYJLkSPg8Yjccj9W5WuAUymiuP/vilB8+L1HqpUQW9bXzlYbI/AICYAIQzv5UN4+sXKA=
    file: 'build/artifacts/appstore/news.tar.gz'
    on:
        repo: owncloud/news
        tags: true

addons:
    firefox: "latest"
